In [1]:
import pandas as pd
import numpy as np

load data sets

In [2]:
from google.colab import files
uploaded = files.upload()

Saving amazon_utf8.csv to amazon_utf8.csv

read the file

In [3]:
df = pd.read_csv("amazon_utf8.csv")
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269"
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4,"43,994"
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928"
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363"
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905"

verify the name

In [4]:
import os
os.listdir()

['.config', 'amazon_utf8.csv', 'sample_data']

check dataset structure

In [5]:
df.shape

(1465, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
dtypes: object(8)
memory usage: 91.7+ KB

check missing value

In [7]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
dtype: int64

create main category

In [8]:
df["Main_Category"] = df["category"].str.split("|").str[0]

In [9]:
df[["category","Main_Category"]].head()

                                            category          Main_Category
0  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
1  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
2  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
3  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories
4  Computers&Accessories|Accessories&Peripherals|...  Computers&Accessories

products main category

In [10]:
df["Main_Category"].value_counts()

Main_Category
Electronics              526
Computers&Accessories    453
Home&Kitchen             448
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64

In [13]:
df["rating"].dtype

dtype('float64')

In [14]:
df.groupby("Main_Category")["rating"].mean().sort_values(ascending=False)

Main_Category
OfficeProducts           4.309677
Toys&Games               4.300000
HomeImprovement          4.250000
Computers&Accessories    4.154967
Electronics              4.081749
Home&Kitchen             4.040716
Health&PersonalCare      4.000000
MusicalInstruments       3.900000
Car&Motorbike            3.800000
Name: rating, dtype: float64

Top 10 highest rated products

In [15]:
top_rated = df.sort_values("rating", ascending=False)[["product_name","rating"]].head(10)

top_rated

                                           product_name  rating
174   Syncwire LTG to USB Cable for Fast Charging Co...     5.0
324   REDTECH USB-C to Lightning Cable 3.3FT, [Apple...     5.0
775   Amazon Basics Wireless Mouse | 2.4 GHz Connect...     5.0
1299  Instant Pot Air Fryer, Vortex 2QT, Touch Contr...     4.8
1201  Oratech Coffee Frother electric, milk frother ...     4.8
1145  Swiffer Instant Electric Water Heater Faucet T...     4.8
1223  FIGMENT Handheld Milk Frother Rechargeable, 3-...     4.7
1226  Zuvexa USB Rechargeable Electric Foam Maker - ...     4.7
1275  Multifunctional 2 in 1 Electric Egg Boiling St...     4.7
459   Spigen EZ Fit Tempered Glass Screen Protector ...     4.7

Top 10 most reviewed products

In [16]:
top_reviewed = df.sort_values("rating_count", ascending=False)[["product_name","rating_count"]].head(10)

top_reviewed

                                           product_name rating_count
1279  Eureka Forbes car Vac 100 Watts Powerful Sucti...          992
750        Eveready Red 1012 AAA Batteries - Pack of 10          989
977   Sennheiser CX 80S in-Ear Wired Headphones with...       98,250
1059  Pigeon 1.5 litre Hot Kettle and Stainless Stee...          976
151   Zoul USB Type C Fast Charging 3A Nylon Braided...          974
32    Zoul USB C 60W Fast Charging 3A 6ft/2M Long Ty...          974
823   Zoul USB C 60W Fast Charging 3A 6ft/2M Long Ty...          974
536   boAt Rockerz 400 Bluetooth On Ear Headphones W...       97,175
918   boAt Rockerz 400 Bluetooth On Ear Headphones W...       97,174
1165  Kitchenwell 18Pc Plastic Food Snack Bag Pouch ...           97

most expensive products

In [20]:
df.sort_values("actual_price", ascending=False)[["product_name","actual_price"]].head(10)

                                           product_name actual_price
653   STRIFF Mpad Mouse Mat 230X190X3mm Gaming Mouse...         ₹999
88    Lapster 65W compatible for OnePlus Dash Warp C...         ₹999
567   Prolet Classic Bumper Case Cover for Samsung G...         ₹999
963   Orico 2.5"(6.3cm) USB 3.0 HDD Enclosure Case C...         ₹999
962   Sounce Gold Plated 3.5 mm Headphone Splitter f...         ₹999
584   boAt BassHeads 100 in-Ear Wired Headphones wit...         ₹999
347   JBL C100SI Wired In Ear Headphones with Mic, J...         ₹999
938   Lapster 1.5 mtr USB 2.0 Type A Male to USB A M...         ₹999
1370  KONVIO NEER 10 Inch Spun Filter (PP SPUN) Cart...         ₹999
923   AirCase Protective Laptop Bag Sleeve fits Upto...         ₹999

cheapest product

In [21]:
df.sort_values("discounted_price")[["product_name","discounted_price"]].head(10)

                                           product_name discounted_price
1033  Prestige PKGSS 1.7L 1500W Electric Kettle (Sta...           ₹1,043
1214  Wipro Vesta 1200 Watt GD203 Heavyweight Automa...           ₹1,049
1311  CSI INTERNATIONAL® Instant Water Geyser, Water...           ₹1,049
1258  CSI INTERNATIONAL® Instant Water Geyser, Water...           ₹1,049
1089  Amazon Basics 2000/1000 Watt Room Heater with ...           ₹1,049
671   ZEBRONICS Zeb-Astra 20 Wireless BT v5.0 Portab...           ₹1,049
1220  Wipro Vesta Electric Egg Boiler, 360 Watts, 3 ...           ₹1,052
560   Lava A1 Josh 21(Blue Silver) -Dual Sim,Call Bl...           ₹1,055
641   Samsung EVO Plus 128GB microSDXC UHS-I U3 130M...           ₹1,059
1281  Candes Gloster All in One Silent Blower Fan Ro...           ₹1,069

average actual price by category

In [23]:
df[df["rating"] > 4.5][["product_name","rating"]]

                                           product_name  rating
137   10k 8k 4k HDMI Cable, Certified 48Gbps 1ms Ult...     4.6
174   Syncwire LTG to USB Cable for Fast Charging Co...     5.0
249   Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...     4.7
324   REDTECH USB-C to Lightning Cable 3.3FT, [Apple...     5.0
447   Spigen EZ Fit Tempered Glass Screen Protector ...     4.6
459   Spigen EZ Fit Tempered Glass Screen Protector ...     4.7
468   Spigen EZ Fit Tempered Glass Screen Protector ...     4.6
571   WeCool S5 Long Selfie Stick, with Large Reinfo...     4.6
775   Amazon Basics Wireless Mouse | 2.4 GHz Connect...     5.0
820   Redgear MP35 Speed-Type Gaming Mousepad (Black...     4.6
853   Logitech Pebble M350 Wireless Mouse with Bluet...     4.6
886   Logitech M331 Silent Plus Wireless Mouse, 2.4G...     4.6
964   Logitech G402 Hyperion Fury USB Wired Gaming M...     4.6
976   Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz R...     4.6
1007  WeCool S5 Long Selfie Stick, with Large Reinfo...     4.6
1119  Lint Remover Woolen Clothes Lint Extractor Bat...     4.6
1127  Ikea 903.391.72 Polypropylene Plastic Solid Be...     4.6
1145  Swiffer Instant Electric Water Heater Faucet T...     4.8
1201  Oratech Coffee Frother electric, milk frother ...     4.8
1216  VRPRIME Lint Roller Lint Remover for Clothes, ...     4.6
1223  FIGMENT Handheld Milk Frother Rechargeable, 3-...     4.7
1226  Zuvexa USB Rechargeable Electric Foam Maker - ...     4.7
1275  Multifunctional 2 in 1 Electric Egg Boiling St...     4.7
1289  Aquadpure Copper + Mineral RO+UV+UF 10 to 12 L...     4.6
1293  Melbon VM-905 2000-Watt Room Heater (ISI Certi...     4.6
1299  Instant Pot Air Fryer, Vortex 2QT, Touch Contr...     4.8
1381  Sujata Dynamix DX Mixer Grinder, 900W, 3 Jars ...     4.6
1388  Campfire Spring Chef Prolix Instant Portable W...     4.7
1428  Sujata Dynamix, Mixer Grinder, 900 Watts, 3 Ja...     4.6

In [27]:
df["discount_percentage"].dtype

dtype('O')

In [28]:
df["discount_percentage"] = df["discount_percentage"].str.replace("%","")
df["discount_percentage"] = pd.to_numeric(df["discount_percentage"])

In [29]:
df["discount_percentage"].dtype

dtype('int64')

In [30]:
print("Total Products :", len(df))
print("Average Rating :", df["rating"].mean())
print("Average Discount :", df["discount_percentage"].mean())
print("Total Reviews :", df["rating_count"].sum())

Total Products : 1465
Average Rating : 4.096584699453552
Average Discount : 47.69146757679181
Total Reviews : 242694399479289436316905248711518830411179691439941339194363426973226247681875732840439941304511976815109621629993784703121533489927661842085074976193497435510752487113552576729846210768727151242691209393789792813142697349392595247809259581884003314296017969134899656706422017109131329746452384269734504572727200531492104523877321780602142339853632242699378902287911057672984703710912724269101343489994363425665919771079109722420104541456547158832840131202806242697663587248712581208501035178050517175901121131313219513759212594523828638128351269284695384703280632958142301137610753664195120850268524780285179692608813835492919300233872119741629930411464212195110480242543565625577325757711931312034316116558231694703142326515612937826859378576313295767361355254511091113552280635030023400317881771094904916193783284073187894072399264083944054323164831422493392719774977858392811067531237188723562426942511611508763624647991056261418425177212525674666147443124229051209114236255123613351972879110752974629559353231852117937817963587429626519436334540871410576731810322447028535877897282161151310456347330023710951328407081657523nan137612110751001112302254517310291555471489617121335214184741121532516387216515101061293049328403906212658381431512002275381712750814542951nan6753351815108381363011976321252190213937276961783117891278071741517415780778076725910689128311217961925902845816212796142823637136725928415970178912463998891302542263622318672591899813937294712231821350139372427031383631383613937127961418517159517943993192527928139371279616801324614648276963291625824746237817302541783194364169052031169622338214003685991899836371319252732487042641439017415139618202189981102922318178672221283118399614003618678151891899848449178313041143994131518998599950772133912582414404113393626326251925219252258241616791668530907178912128311192529436472221899832916266036795012831194991777585062135022639378476821796178337779171294969154441518757213503153981561292844399432341304531383220879264628978314593771925891655718998165572191629472194993773723511925321807571441518654319726880217969499560983182294995077271482085018434924415672602770450772925883182224075824870828937822638135522147596194921803153924511541193147588911046662838031822307514266388799717567260119108338188164147408866839987125384674412681363846491102295077218011440430513762263823527142005214547732214731383246527790602142324527630254171611414560315693407682897818998497115263637111369542770917833253105613147354180998690672621068914184124791217641925871071512179792995875114283642735431515973025422638770272882929478331766866424269280305792147789177017162206337174399479285179508103369118279436415295271399504169053005869619338210986457604955116167721372140035248707199139615233557471496192752832464418139720349113568339010305218678151891217912958825811716350245519211946696383373530411304433584177959991339126556259035346448448517686146002630662102348524269728618326254018116872262110159511647682302267951442645671379715137187578151566389344487520881474412452178105364820145958382216470517129119761734887798244321891049311247521272011096216299315347571653793772101035176389912153573025488544051949122478724120457861016557108715404019385925883454157901496942139989196243201304699940775868409309590325771273189378528662722382356571926880169027668372711320850280419862451232619415783805328092591011736422241184146291528150326958514371318225886473673005203982125113302744125523174202181107474976256074122625811833117793888656929251269173949169103050273674212081933250063343463012261897420342742926423313051121310174174136676807635518656315991075139712492135525752523352166273523441934089511006893843084621076861065250365057853797922450676117399985852362205052909040991296644281209356922118802176222375245313544109763061227276018131421942775555692595123755882108331044343419133029262824780107186233105418188107518173638436063571017045987222127131432193887945417604248544696856613049166809717436865941218526239701158676561072530257064573672563102620434149744139851952242013132284427136713199297462806303552868670353061834197317442645237109224931267921041991440311113107736491139441076025996161468280450142372066816747689555420053334428869825075149258550725985773294271780230125356912740602348214236199166747232286013572161822908536237549514081926479873332453652251510576495921111462323911884181526127101341552252621233651330018543357820314499427056331783260263350540321559248591412084272331665301192429612348421783140306398440502424741349107411632573601780903138813653803797417218900976492735432732143683972497912891244625340309641194010613029291154536044664732331282702616416166356931439179461765140621564611196951772114992162196211999810511716329311742418891032453553366101778718462629152762981246679499515582654336884383478237124146676424410171299931142382781109071325043070118281240208694411034371266355121316516461799461088661340653803546529244445841494715591660132286298446111991118114353185142903036129619971771150343242283214983051191404931609650384629022069349578933138371145649497819961811219813127586510674881112174346642112273790191023455028135321381679128378873768132297721849753172828772505178794157294580140428107172921164635472293842646180225278074202659111964253160155889581325113931372411602014703663638355211148244922996027461282927574332894238157988925437076192593356634740296185195495910153973230020344110308992471631316630356280951091538251371246186315972745911170306510213964894897722333045704867529877863725206638397326352761731453517325912271195771406871045112065611988374044016112162976055386557228811061193550591573584189915252416624227951602311588327111004319532313246241442280340144727832571644106679683195145659014364184693130682326100464006311811888655018461085290497344022259153226016727945136713132126527375510652377256959671776420029738581681014074140837395891777141606919287287388827497122935241564908271013327517712536780153489812021108171042931925873137915272686178266421224186845115939653122219522831127113251855021090411846880316987